- name: 生成 apiserver 配置文件
  template:
    src: "{{ item.srcfile }}"
    dest: "{{ item.destfile }}"
  with_items:
    - { srcfile: 'templates/config.j2', destfile: '/etc/kubernetes/config' }
    - { srcfile: 'templates/apiserver.j2', destfile: '/etc/kubernetes/apiserver' }
- name: 生成 controller-manager 配置文件
  template:
    src: "{{ item.srcfile }}"
    dest: "{{ item.destfile }}"
  with_items:
    - { srcfile: 'templates/controller-manager.j2', destfile: '/etc/kubernetes/controller-manager' }
- name: 生成 kube-scheduler 配置文件
  template:
    src: "{{ item.srcfile }}"
    dest: "{{ item.destfile }}"
  with_items:
    - { srcfile: 'templates/scheduler.j2', destfile: '/etc/kubernetes/scheduler' }
- name: 准备 apiserver 启动文件
  copy:
    src: files/kube-apiserver.service
    dest: /usr/lib/systemd/system/kube-apiserver.service
  notify:
  - start kube-apiserver
- name: 准备 kube-controller-manager 启动文件
  copy:
    src: files/kube-controller-manager.service
    dest: /usr/lib/systemd/system/kube-controller-manager.service
  notify:
  - start kube-controller-manager
- name: 准备 kube-scheduler 启动文件
  copy:
    src: files/kube-scheduler.service
    dest: /usr/lib/systemd/system/kube-scheduler.service
  notify:
  - start kube-scheduler
