- name: start flanneld
  service:
    name: flanneld
    state: restarted
    daemon_reload: yes
    enabled: yes
- name: restart docker
  service:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes
