- name: 准备 kubernets 证书目录
  file:
    path: "{{ ssl_dir }}"
    state: directory

- name: 创建 etcd 证书依赖文件
  template: src="templates/etcd_ssl.cnf.j2" dest={{ ssl_dir }}/etcd_ssl.cnf

- name: 创建 kubernetes 证书依赖文件
  template: src="templates/master_ssl.cnf.j2" dest={{ ssl_dir }}/master_ssl.cnf

- stat: path={{ etcd_cert }}
  register: etcd_ssl

- name: 创建 ca 机构 和 etcd 证书
  when: not etcd_ssl.stat.exists
  command: "{{ item }}"
  with_items:
    - "openssl genrsa -out {{ ca_key }} 2048"
    - "openssl req -x509 -new -nodes -key {{ ca_key }} -subj '/CN=kubernetes' -days 10000 -out {{ ca_cert }}"
    - "openssl genrsa -out {{ etcd_key }} 2048"
    - "openssl req -new -key {{ etcd_key }} -subj '/CN=etcd' -config {{ ssl_dir }}/etcd_ssl.cnf -out {{ etcd_csr }}"
    - "openssl x509 -req -in {{ etcd_csr }} -CA {{ ca_cert }} -CAkey {{ ca_key }} -CAcreateserial -days 10000 -extensions v3_req -extfile {{ ssl_dir }}/etcd_ssl.cnf -out {{ etcd_cert }}"

- stat: path={{ apiserver_client_cert }}
  register: kube_ssl

- name: 创建 kubernets 证书
  when: not kube_ssl.stat.exists
  command: "{{ item }}"
  with_items:
    - "openssl genrsa -out {{ apiserver_key }} 2048"
    - "openssl req -new -key {{ apiserver_key }} -subj '/CN=kube-apiserver' -config {{ ssl_dir }}/master_ssl.cnf -out {{ apiserver_csr }}"
    - "openssl x509 -req -in {{ apiserver_csr }} -CA {{ ca_cert }} -CAkey {{ ca_key }} -CAcreateserial -days 10000 -extensions v3_req -extfile {{ ssl_dir }}/master_ssl.cnf -out {{ apiserver_cert }}"
    - "openssl genrsa -out  {{ admin_key }} 2048"
    - "openssl req -new -key {{ admin_key }} -subj '/CN=admin/O=system:masters'  -out {{ admin_csr }}"
    - "openssl x509 -req -in {{ admin_csr }} -CA {{ ca_cert }} -CAkey {{ ca_key }} -CAcreateserial -days 10000 -extensions v3_req -out {{ admin_cert }}"
    - "openssl genrsa -out  {{ apiserver_client_key }} 2048"
    - "openssl req -new -key {{ apiserver_client_key }} -subj '/CN=kube-apiserver-client/O=system:masters'  -out {{ apiserver_client_csr }}"
    - "openssl x509 -req -in {{ apiserver_client_csr }} -CA {{ ca_cert }} -CAkey {{ ca_key }} -CAcreateserial -days 10000 -extensions v3_req -out {{ apiserver_client_cert }}"
